version: '3'

services:
  #database
  db-test:
    
    image: mysql:5.7
    volumes: 
      - db-test_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password  
      MYSQL_DATABASE: wordpress
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    networks:
      - wpsite
  #phpmyadmin
  phpmyadmin:
    depends_on:
      - db-test
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8086:80'   
    environment:
      PMA_HOST: db-test
      MYSQL_ROOT_PASSWORD: password    
    networks:
      - wpsite
  #wordpress    
  wordpress:
    depends_on:
      - db-test
    image: wordpress:latest
    ports:
      - '8084:80'
    restart: always
    volumes: ['./:/var/www/thml']
    environment:
      WORDPRESS_DB_HOST: db-test:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_NAME: wordpress
    networks: 
      - wpsite
networks:
  wpsite:
volumes:
  db-test_data:  